//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XInputBatteryMeter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XInputBatteryMeter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About XInput Battery Meter.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Game Controller by Uriel Sosa from the Noun Project.
        /// </summary>
        internal static string AcknowledgementsControllerIconAck {
            get {
                return ResourceManager.GetString("AcknowledgementsControllerIconAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC BY 3.0 US.
        /// </summary>
        internal static string AcknowledgementsControllerIconLicense {
            get {
                return ResourceManager.GetString("AcknowledgementsControllerIconLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Game Controller icon:.
        /// </summary>
        internal static string AcknowledgementsControllerIconTitle {
            get {
                return ResourceManager.GetString("AcknowledgementsControllerIconTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License.
        /// </summary>
        internal static string AcknowledgementsSharpDxLicense {
            get {
                return ResourceManager.GetString("AcknowledgementsSharpDxLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpDX:.
        /// </summary>
        internal static string AcknowledgementsSharpDxTitle {
            get {
                return ResourceManager.GetString("AcknowledgementsSharpDxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string AcknowledgementsTitle {
            get {
                return ResourceManager.GetString("AcknowledgementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a battery meter for connected XInput controller devices in the Windows taskbar..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XInput Battery Meter.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon batteryIcon_0 {
            get {
                object obj = ResourceManager.GetObject("batteryIcon_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon batteryIcon_100 {
            get {
                object obj = ResourceManager.GetObject("batteryIcon_100", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon batteryIcon_33 {
            get {
                object obj = ResourceManager.GetObject("batteryIcon_33", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon batteryIcon_66 {
            get {
                object obj = ResourceManager.GetObject("batteryIcon_66", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Level: .
        /// </summary>
        internal static string BatteryLevelDescriptor {
            get {
                return ResourceManager.GetString("BatteryLevelDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATTERY_LEVEL.
        /// </summary>
        internal static string BatteryLevelPlaceholder {
            get {
                return ResourceManager.GetString("BatteryLevelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battery in Controller USER_INDEX is low..
        /// </summary>
        internal static string BatteryLowDescription {
            get {
                return ResourceManager.GetString("BatteryLowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Low.
        /// </summary>
        internal static string BatteryLowTitle {
            get {
                return ResourceManager.GetString("BatteryLowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Type: .
        /// </summary>
        internal static string BatteryTypeDescriptor {
            get {
                return ResourceManager.GetString("BatteryTypeDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATTERY_TYPE.
        /// </summary>
        internal static string BatteryTypePlaceholder {
            get {
                return ResourceManager.GetString("BatteryTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller USER_INDEX has been connected..
        /// </summary>
        internal static string ControllerConnectedDescription {
            get {
                return ResourceManager.GetString("ControllerConnectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Connected.
        /// </summary>
        internal static string ControllerConnectedTitle {
            get {
                return ResourceManager.GetString("ControllerConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller .
        /// </summary>
        internal static string ControllerDescriptor {
            get {
                return ResourceManager.GetString("ControllerDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller USER_INDEX has been disconnected..
        /// </summary>
        internal static string ControllerDisconnectedDescription {
            get {
                return ResourceManager.GetString("ControllerDisconnectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Disconnected.
        /// </summary>
        internal static string ControllerDisconnectedTitle {
            get {
                return ResourceManager.GetString("ControllerDisconnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControllerIcon {
            get {
                object obj = ResourceManager.GetObject("ControllerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://thenounproject.com/term/video-game-controller/8357/.
        /// </summary>
        internal static string ControllerIconUrl {
            get {
                return ResourceManager.GetString("ControllerIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://creativecommons.org/licenses/by/3.0/us/.
        /// </summary>
        internal static string CreativeCommonsUrl {
            get {
                return ResourceManager.GetString("CreativeCommonsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMenuItem {
            get {
                return ResourceManager.GetString("ExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2017 Martin Tracey
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this perm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not connnected..
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller USER_INDEX
        ///Type: BATTERY_TYPE
        ///Level: BATTERY_LEVEL.
        /// </summary>
        internal static string NotificationIconText {
            get {
                return ResourceManager.GetString("NotificationIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sharpdx.org/License.txt.
        /// </summary>
        internal static string SharpdxLicenseUrl {
            get {
                return ResourceManager.GetString("SharpdxLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_INDEX.
        /// </summary>
        internal static string UserIndexPlaceholder {
            get {
                return ResourceManager.GetString("UserIndexPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        internal static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
    }
}
